### ISSUE TITLE
Template dir needs changing for PHP8 

### ISSUE THREAD

**Issue by ErikHommel** [agileware/au.com.agileware.membershiprelationshiptypeeditor#2]
Line 99 in the civix.php file

` if (is_array($template->template_dir)) {
    array_unshift($template->template_dir, $extDir);
  }
  else {
    $template->template_dir = array($extDir, $template->template_dir);
  }`

 needs changing to

` $template->addTemplateDir($extDir);`

Do you want a PR?

**Comment by agileware-justin** [comment]
@ErikHommel thanks - all good. I'll update and advise.

**Comment by agileware-justin** [comment]
Try using 1.5.1 which has civix regenerated.
